name: Deploy React Application in BeanStalk

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the source code
      - name: Checkout source code
        uses: actions/checkout@v2

      # Install dependencies and build the React app
      - name: Install dependencies and build React app
        run: |
          npm install
          npm run build

      # Generate deployment package
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      # **Safe Cleanup Before Deployment**
      - name: Stop and Remove Old Containers
        run: |
          # Stop all running containers (only if any exist)
          RUNNING_CONTAINERS=$(docker ps -q)
          if [ ! -z "$RUNNING_CONTAINERS" ]; then
            docker stop $RUNNING_CONTAINERS
            docker rm $RUNNING_CONTAINERS
          else
            echo "No running containers to stop."
          fi

      - name: Remove Old Docker Images
        run: |
          OLD_IMAGES=$(docker images -q my-react-app)
          if [ ! -z "$OLD_IMAGES" ]; then
            docker rmi -f $OLD_IMAGES
          else
            echo "No old images to remove."
          fi
          
          docker system prune -f  # Clean up unused resources

      # Deploy to Elastic Beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ecommerce-app
          environment_name: Ecommerce-app-env
          version_label: ${{ github.sha }}
          existing_bucket_name: elasticbeanstalk-ap-south-1-869935081261
          region: ap-south-1
          deployment_package: deploy.zip
